version: '3.8'
services:
  ingesta01:
    build:
      context: ./ingesta01
    volumes:
      - ./ingesta01:/app
      - /home/ubuntu/.aws:/root/.aws  
    command: >
      bash -c "while true; do python ingesta01.py && sleep 3600; done"
  
  ingesta02:
    build:
      context: ./ingesta02
    volumes:
      - ./ingesta02:/app
      - /home/ubuntu/.aws:/root/.aws 
    command: >
      bash -c "while true; do python ingesta02.py && sleep 3600; done"

  ingesta03:
    build:
      context: ./ingesta03
    volumes:
      - ./ingesta03:/app
      - /home/ubuntu/.aws:/root/.aws
    command: >
      bash -c "while true; do python ingesta03.py && sleep 3600; done"
