version: '3.8'
services:
  ingesta01:
    build:
      context: ./ingesta01
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - S3_BUCKET=bucket-para-ingesta
    volumes:
      - ./ingesta01:/app
    command: >
      bash -c "while true; do python app.py && sleep 3600; done"
  
  ingesta02:
    build:
      context: ./ingesta02
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - S3_BUCKET=bucket-para-ingesta
    volumes:
      - ./ingesta02:/app
    command: >
      bash -c "while true; do python app.py && sleep 3600; done"

  ingesta03:
    build:
      context: ./ingesta03
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - S3_BUCKET=bucket-para-ingesta
    volumes:
      - ./ingesta03:/app
    command: >
      bash -c "while true; do python app.py && sleep 3600; done"
